name: Build Python Executables

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py

      - name: Rename output
        run: |
          mkdir dist-out
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main.exe dist-out/augment-free-windows.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/main dist-out/augment-free-mac
          else
            mv dist/main dist-out/augment-free-linux
          fi
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist-out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
